version: '3.4'

services:
  crash-report-collector:
    container_name: crash-report-collector
    image: crash-report-collector
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - DATA_DIR=/data
      - COLLECT_ONLY=1
    volumes:
      - ./CRS_DATA:/data
    ports:
      - 8080:8080
      - 8081:8081
